spring:
  application:
    name: customer-service
server:
  port: 1901
com:
  bkk:
    sm:
      mongo:
        customers:
          database: customers
          uri: mongodb+srv://${MONGO_CUSTOMER_USER}:${MONGO_CUSTOMER_PASSWORD}@${MONGO_URL}
          init:
            enable: true
            superuser:
              username: ${CUSTOMER_SUPER_USER}
              password: ${CUSTOMER_SUPER_USER_PASSWORD}
              firstname: ${CUSTOMER_SUPER_USER_FIRSTNAME}
              lastname: ${CUSTOMER_SUPER_USER_LASTNAME}
              email: ${CUSTOMER_SUPER_USER_EMAIL}
management:
  health:
    probes:
      enabled: true
