{{- if .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  namespace: {{.Values.deployments.namespace}}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  namespace: {{ .Values.deployments.namespace | default .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  namespace: {{.Values.deployments.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helm.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}
