apiVersion: v1
entries:
  sm-customer:
    - apiVersion: v2
      appVersion: 0.1.7
      created: "2024-05-25T20:31:26.463993294Z"
      description: A Helm chart for Sports Management Customer microservice
      digest: 24c2412a1ccd18b5253b6aa0276dd5ffebcb3871c2f8732d6a333bc62d7dd335
      name: sm-customer
      type: application
      urls:
        - https://raw.githubusercontent.com/kdavid76/sm-customer/gh-pages/charts/sm-customer-0.1.16.tgz
      version: 0.1.16
generated: "2024-05-25T20:31:26.45450955Z"
